version: "3.4"

services:
  finalassignment10:
    image: dammdeol/finalassignment10
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000